app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail')
]

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="es">
<head>
    <title>Aranda {% block head_title %}{% endblock %}</title>
    
 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="manifest" href="{% static 'icons/manifest.json' %}">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    
  <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'core/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'core/css/animate.css' %}" rel="stylesheet" media="all" type="text/css">
  <link href="{% static 'core/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'core/owl-carousel/owl.carousel.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2">
                        <div>
                            <a href="{% url 'home' %}">
                                <img class="img-fluid" src="{% static 'images/logg.png' %}" style="max-width: 280px;"/>
                            </a>
                        </div>
                    </div>
                        
     
                    

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'profile' %}"><span><i class="fas fa-user"></i></span></a>
                                    {% else %}
                                        <a href="{% url 'account_login' %}"><span><i
                                                class="fas fa-sign-in-alt"></i></span></a>
                                    {% endif %}
                                </li>
                                <li>
                                    <a href="{% url 'cart:summary' %}" class="site-cart">
                                        <span><i class="fas fa-shopping-cart"></i></span>
                                        <span class="count">{{ request|cart_item_count }}</span>
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0">
                                    <a href="#" class="site-menu-toggle js-menu-toggle">
                                        <span><i class="fas fa-bars"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                    <span class="alert-inner--text">{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

    </header>

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}

</div>

{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}


</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href={% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Contacto</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Ponerse en contacto</h2>
            </div>

            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Enviar Mensaje"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/footer.html
 <footer id="footer" style="position: relative;">
        <div class="container">
          <div class="wrap-footer">
            <div class="row">
              <div class="col-md-7">
                <div class="footer-contact-form">
                  <h2 class="footer-title">INFORMACIÓN</h2>
                  <form name="" method="post" action="contact.php">
                    <div class="row">
                      <div class="col-md-6">
                        
                       <div id=tabla1>
                        <div id=cabtab1>
                            Fundador: Annibal Aranda
                        </div>
                        <div id=cuerpotab1>
                            
                        </div>
                        </div>
                        
                      </div>
                      
                    </div>
                  </form>
                </div>
              </div>
              
              <div class="col-md-5">
                <div class="footer-contact-info">
                  <div class="contact-info-item">
                    <div class="row">
                      <div class="col-md-1">
                        <div class="contact-info-icon">
                          <i class="fa fa-map-marker"></i>
                        </div>
                      </div>
                      <div class="col-md-10">
                        <h3>Localización</h3>
                        <p> Argentina </p>
                      </div>
                    </div>
                  </div>
                  <div class="contact-info-item">
                    <div class="row">
                      <div class="col-md-1">
                        <div class="contact-info-icon">
                          <i class="fa fa-phone"></i>
                        </div>
                      </div>
                      <div class="col-md-10">
                        <h3>Numero de contacto</h3>
                        <p> +54 9 11 6114-1861 </p>
                      </div>
                    </div>
                  </div>
                  <div class="contact-info-item">
                    <div class="row">
                      <div class="col-md-1">
                        <div class="contact-info-icon">
                          <i class="fa fa-envelope"></i>
                        </div>
                      </div>
                      <div class="col-md-10">
                        <h3>Email</h3>
                        <p>arandaM@gmail.com</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>
          <div class="bottom-footer">
            <ul class="list-inline footer-link link">
              <li><a href="https://www.facebook.com">Facebook</a></li>
               <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
              <li><a href="twitter.com">Twitter</a></li>
               <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>

            </ul>
            <div class="copyright">
              <span>Copyright © 2020 <a href="#" target="_blank">.NETMOTION</a></span>
            </div>
          </div> 
        </div>
      </footer>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="site-blocks-cover" style="background-image: url({% static 'images/mueble1.jpg' %});" data-aos="fade">
    <div class="header-text">
       	<div >
            <h1>Aranda Amoblamientos</h1>
            <p>Los Mejores Estilos De Tu Hogar</p>
        </div>
    </div><!-- /header-text -->
</div>

{% endblock content %}

templates/navbar.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/">Inicio</a></li>
            <li><a href="{% url 'cart:product-list' %}">Productos</a></li>
            <li><a href="{% url 'contact' %}">Contacto</a></li>
            {% if request.user.is_staff %}
                <li><a href="/">Personal</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/order.html
{% extends "base.html" %}

{% block content %}
<div class="site-sectino">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-m-12">
                <a href="{% url 'profile' %}">Back to Profile</a>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            Order: #{{ order.reference_number }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">Ordered on: {{ order.ordered_date }}</h6>
                    </div>
                    <hr />
                    
                    <div class="site-blocks-table">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Producto</th>
                                    <th>Total</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order.items.all %}
                                <tr>
                                    <td>{{ item.size.name }}, {{ item.colour.name }} of {{ item.product.title }} x {{ item.quantity }}</td>
                                    <td>${{ item.get_total_item_price }}</td>
                                </tr>
                                
                                {% endfor %}

                                <tr>
                                    <td>Subtotal</td>
                                    <td>${{ order.get_subtotal }}</td>
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <td>${{order.get_total}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="site-sectino">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-m-12">
                <h2 class="text-black">MI PERFIL</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ request.user.email }}</h5>
                        <a href="{% url 'account_logout' %}"><small class="float-right">Logout</small></a>
                    </div>
                    <hr />
                    <h5 class="card-title">TUS ORDENES</h5>
                    <div class="site-blocks-table">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No.Referencia.</th>
                                    <th>Fecha</th>
                                    <th>Cantidad</th>
                                    <th>Estado de Pago</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <a href="{% url 'cart:order-detail' order.pk %}"><td>#{{ order.reference_number }}</td></a>
                                    <td>{{ order.ordered_date }}</td>
                                    <td>{{ order.get_total }}</td>
                                    <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="4">You havent made any purchases</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script src="{% static 'core/js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
<script src="{% static 'core/js/jquery.localScroll.min.js' %}"></script>
<script src="{% static 'core/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'core/js/SmoothScroll.js' %}"></script>
<script src="{% static 'core/js/wow.min.js' %}"></script>
<script src="{% static 'core/owl-carousel/owl.carousel.js' %}"></script>
<script src="{% static 'core/js/main.js' %}"></script>